### ISSUE TITLE
How to use instructions?

### ISSUE THREAD

**Issue by pavelpoley** [monkey0506/jobbifier#4]
Can you give some instructions how to use it? i have same issue with FAT full and my assets file only 260 MB size on disk.

**Comment by PippoApps** [comment]
Download the file in the /lib folder of sdk.
I renamed it as jobb_new.jar
Then modify the jobb.bat to use that file.
`set CLASSPATH=%APP_HOME%\lib\jobb_new.jar;%APP_HOME%\lib\fat32lib.jar`
Security-wise it is risky to just execute a random jar found on github, but it did work for me :)
big thanks to the author

**Comment by monkey0506** [comment]
I'm sorry that I had overlooked this issue being posted, but the compiled JAR command line tool is functionally identical to the `jobb` JAR shipped [alongside the Android SDK](https://developer.android.com/studio/command-line/jobb) (with the file size formatting fixes, of course). The GUI is meant to be self-explanatory (being a simple GUI wrapper over the command line tool).

However, this project became deprecated in August 2021 when Google officially deprecated the use of OBB asset files in favor of the new [Play Asset Delivery](https://developer.android.com/guide/playcore/asset-delivery). The tool itself still performs the intended task, but the specific use-case for which it was designed no longer exists outside of legacy platforms.

`Security-wise it is risky to just execute a random jar found on github`

@PippoApps while this advice is certainly true of *any* executable code found online (whether in compiled binary form or you blindly compile the code yourself), it does come across perhaps a bit provocative, or at the least denigrating to the author(s) when the code is open-source, freely available, and the executable in question is produced by CI (which has a [free and open-source configuration file](../blob/master/.travis.yml)). Any malformed or otherwise harmful aspects of this code, if such exists (none are known to me), are demonstrably artifacts of the respective source files this project was built on top of, rather than anything newly introduced in this repo.

Admittedly, I made an error when I created this repo by not cloning the `jobb` and `libfat32` sources, rather just copying them and losing all version history. This mistake does of course make it much harder to verify the changes that I actually made (I can't exactly `git diff` without the exact files I originally copied). [This StackOverflow question](https://stackoverflow.com/questions/18906055/what-causes-jobb-tool-to-throw-fat-full-ioexception/18926248#18926248) (and related questions linked in the comments) explain that the two fixes this repository contains are to correct the file size based formatting in `libfat32` and to force `jobb` to always use `FAT16` format for any total file sizes under 2 GB, as this file format was **required** by the Android API functions (e.g., [mountObb](https://developer.android.com/reference/android/os/storage/StorageManager.html#mountObb(java.lang.String,%20java.lang.String,%20android.os.storage.OnObbStateChangeListener))).

That being said, thank you for your response, bringing my attention to this long-standing open issue.

**Comment by PippoApps** [comment]
True.
I did try to work with OBB before doing homework and finding out it is a deprecated solution.
I lost half day before finding out. Luckily your jar did save me some time though.
Very grateful.
All the best
F

**Comment by PippoApps** [comment]
> `Security-wise it is risky to just execute a random jar found on github`
> 
> @PippoApps while this advice is certainly true of _any_ executable code found online (whether in compiled binary form or you blindly compile the code yourself), it does come across perhaps a bit provocative, or at the least denigrating to the author(s) when the code is open-source, freely available, and the executable in question is produced by CI (which has a [free and open-source configuration file](../blob/master/.travis.yml)). Any malformed or otherwise harmful aspects of this code, if such exists (none are known to me), are demonstrably artifacts of the respective source files this project was built on top of, rather than anything newly introduced in this repo.

I am so sorry, please do not misunderstand my words.
I did put a smiley to underline that my sentence wasn't to be taken seriously, but I wrote it with no intention to be rude.
Your jar saved my day and definitely saved me extra hours of (lost, since obb are deprecated) effort.
No provocation or denigration intended, on the contrary, I did download and execute it with no hesitation.
Please accept my apologies.

**Comment by monkey0506** [comment]
@PippoApps I didn't take the comment too harshly, but just wanted to comment that it could come across as unfair given that the code is open source. And like I said, I made mistakes in the way I originally published the code in the first place, so no harm done. Thanks again to you for your feedback.
